version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: ${PG_NAME}
    env_file:
      - stack.env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    volumes:
      - ${PG_PATH}:/var/lib/postgresql/data